### ISSUE TITLE
Missing requirement requests

### ISSUE THREAD

**Issue by b2m** [nlpcloud/nlpcloud-python#1]
This python package depends on the [requests](https://pypi.org/project/requests/) package, but `requests` is not declared as a dependency. The corresponding error will only occur during runtime and on a clean system where `requests` is not already installed.

Code snippet to reproduce the error using Docker:

```shell
shell> docker run -it --rm python:3.9 /bin/bash
root@docker:/# pip install nlpcloud
...
Successfully installed nlpcloud-1.0.9
root@docker:/# python
...
>>> import nlpcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/nlpcloud/__init__.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

As there are more ways to declare python dependencies as I have space to list here I will just mention the most direct solution: add a [install_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires) to your `setup.py`.

**Comment by juliensalinas** [comment]
Thanks @b2m , we'll work on this asap!

**Comment by juliensalinas** [comment]
This is fixed!
Thanks for raising this and please don't hesitate to reopen if needed.
