### ISSUE TITLE
Add a timeout parameter would be great

### ISSUE THREAD

**Issue by AndersonBY** [nlpcloud/nlpcloud-python#2]
Hi! I think a timeout parameter would be great because occasionally I can't connect to nlpcloud because of network connection problem. So with a timeout parameter I can let my program to retry when timeouted.

Thanks.

**Comment by juliensalinas** [comment]
Thanks @AndersonBY this is definitely something we are considering!

**Comment by dahifi** [comment]
@AndersonBY I'm looking at Temporal.io to deal with outages. Basically wrap the API call in an activity, and it will retry forever.
