### ISSUE TITLE
Missing models for classification

### ISSUE THREAD

**Issue by ernests** [nlpcloud/nlpcloud-python#4]
Tested examples from Playground - https://nlpcloud.com/home/playground/classification

Examples with models "finetuned-gpt-neox-20b" and "fast-gpt-j" work in Playground but not with the nlpcloud-python library. 

`HTTPError: 404 Client Error: Not Found for url: https://api.nlpcloud.io/v1/fast-gpt-j/classification: 404 page not found`

I suppose endpoint has changed for these models.

**Comment by ernests** [comment]
Figured it out. 

In copied example `gpu` is set to `False` (because I didn't tick Use GPU). But there is no endpoint without gpu. If `gpu=True` it will use `https://api.nlpcloud.io/v1/gpu/fast-gpt-j/classification` endpoint and it works.

**Comment by ernests** [comment]
`multi-class` option is irrelevat for these two models. Always returns single category with 1. Maybe there are some parameters which are not available publicly?

**Comment by juliensalinas** [comment]
Hello @ernests thanks so much for pointing this. Indeed our code conversion in the Playground should be fixed. We'll have a look at the soon!
Great to see that you found the solution so quickly.

You're right about multi class. This parameter is ignored with Fast GPT-J. This is actually mentioned in our documentation (https://docs.nlpcloud.com/#classification) but maybe not in our Playground. We'll have a look!

Thanks again.
