### ISSUE TITLE
Simple import give me nlpcloud' has no attribute 'Client' (most likely due to a circular import)

### ISSUE THREAD

**Issue by slamer59** [nlpcloud/nlpcloud-python#5]
client = nlpcloud.Client(
             ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'nlpcloud' has no attribute 'Client' (most likely due to a circular import)

with nlpcloud 1.0.41

**Comment by slamer59** [comment]
In pip this is the best version we have when in github it is tag v1.1.41

https://pypi.org/project/nlpcloud/

Maybe a github taging problem ?

**Comment by juliensalinas** [comment]
Hello @slamer59 thanks for you message,
Such an error usually happens when you have a directory that has the same name as the library that you are trying to import.
Maybe you have a folder called "nlpcloud" that is messing up with your lib import?
