### ISSUE TITLE
Mismatch of versions

### ISSUE THREAD

**Issue by fabaff** [nlpcloud/nlpcloud-python#6]
The `setup.py` file says [1.0.43](https://github.com/nlpcloud/nlpcloud-python/blob/v1.1.43/setup.py#L5C12-L5C12) which matches the releaee on PyPI ([1.0.43](https://pypi.org/project/nlpcloud/1.0.43/)) but the tag on GitHub says [1.1.43](https://github.com/nlpcloud/nlpcloud-python/releases/tag/v1.1.43).

It would be appreciated if you could align the release numbering as for distribution packages this is sub-optimal.

Thanks

**Comment by juliensalinas** [comment]
Thank you @fabaff . Done!
