### ISSUE TITLE
phone verification isnt working

### ISSUE THREAD

**Issue by NeuralNoble** [nlpcloud/nlpcloud-python#7]
after email verification it asks for number and i just enter the phone number for the first time in my life and it says too many requests contact support .

**Comment by juliensalinas** [comment]
Hello @NeuralNoble,

This is because we need to perform security verifications on your account before validating it.
Could you please answer our support email? Our validation process is quite fast.

Looking forward to hearing from you!

Best,

Julien

**Comment by NeuralNoble** [comment]
you are asking for sensitive informations
